# Generated by Django 5.0.7 on 2024-07-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer_generate_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FineTunedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VectorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vectorid', models.CharField(max_length=250)),
                ('assistantid', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
